apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment
  namespace: sandbox-namespace
  labels:
    app: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: web
          image: [account-id].dkr.ecr.ca-central-1.amazonaws.com/sandbox-namespace/web:[version]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password 
            - name: MONGODB_URI
              value: 'mongodb://[db-user]:$(MONGODB_PASS)@[hostname]:27017/?authSource=[db-name]'
