apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment
  namespace: sandbox-namespace
  labels:
    app: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
        - name: web
          image: [account-id].dkr.ecr.ca-central-1.amazonaws.com/sandbox-namespace/web:[version]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: secret-key
            - name: MONGODB_URI
              value: 'mongodb://[db-user]:$(MONGODB_PASS)@[hostname]:27017/?authSource=[db-name]'
      serviceAccountName: pod-service-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-service-account
  namespace: sandbox-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pod-service-account
  namespace: sandbox-namespace
